// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes the sentiment of news and social media related to a specific stock.
 *
 * - analyzeStockSentiment - A function that analyzes stock sentiment.
 * - AnalyzeStockSentimentInput - The input type for the analyzeStockSentiment function.
 * - AnalyzeStockSentimentOutput - The return type for the analyzeStockSentiment function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const AnalyzeStockSentimentInputSchema = z.object({
  ticker: z.string().describe('The ticker symbol of the stock to analyze.'),
});
export type AnalyzeStockSentimentInput = z.infer<typeof AnalyzeStockSentimentInputSchema>;

const AnalyzeStockSentimentOutputSchema = z.object({
  sentimentScore: z.number().describe('A score between -1 and 1 indicating the overall sentiment.  -1 is negative, 0 is neutral, and 1 is positive.'),
  analysis: z.string().describe('A summary of the sentiment analysis.'),
});
export type AnalyzeStockSentimentOutput = z.infer<typeof AnalyzeStockSentimentOutputSchema>;

export async function analyzeStockSentiment(input: AnalyzeStockSentimentInput): Promise<AnalyzeStockSentimentOutput> {
  return analyzeStockSentimentFlow(input);
}

const analyzeSentimentPrompt = ai.definePrompt({
  name: 'analyzeSentimentPrompt',
  input: {
    schema: z.object({
      ticker: z.string().describe('The ticker symbol of the stock to analyze.'),
    }),
  },
  output: {
    schema: z.object({
      sentimentScore: z.number().describe('A score between -1 and 1 indicating the overall sentiment.  -1 is negative, 0 is neutral, and 1 is positive.'),
      analysis: z.string().describe('A summary of the sentiment analysis.'),
    }),
  },
  prompt: `Analyze the sentiment of news articles and social media posts related to {{ticker}}.\n\nDetermine an overall sentiment score between -1 and 1, where -1 is completely negative, 0 is neutral, and 1 is completely positive.\n\nProvide a brief summary of the sentiment analysis.`,
});

const analyzeStockSentimentFlow = ai.defineFlow<
  typeof AnalyzeStockSentimentInputSchema,
  typeof AnalyzeStockSentimentOutputSchema
>({
  name: 'analyzeStockSentimentFlow',
  inputSchema: AnalyzeStockSentimentInputSchema,
  outputSchema: AnalyzeStockSentimentOutputSchema,
},
async input => {
  const {output} = await analyzeSentimentPrompt(input);
  return output!;
});